language: python
python: "2.7"
install:
- virtualenv test-env --no-setuptools
- mkdir -p buildout-cache/downloads
- test-env/bin/python bootstrap.py -c travis.cfg
- bin/buildout -N -t 3 -c travis.cfg
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script: bin/test